Remove jquery require to resolve JS errors
JQuery is already available due to govuk_admin_template. Requiring it
here installs it a second time which causes conflicts.

Removing this resolves two JS errors:

- Uncaught TypeError: e.datepicker is not a function
- Uncaught TypeError: $(...).dropdown is not a function